# Generated by Django 5.0.1 on 2024-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
