# Generated by Django 5.0.1 on 2024-02-23 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-timestamp"]},
        ),
    ]
