# Generated by Django 5.0.1 on 2024-02-23 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_user_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
